name: Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@4bda8a2d5e0ffb6126d83b679319a1040f292b6d
        with:
          feed-url: https://david.gardiner.net.au/feed.xml
          readme-section: posts
          empty-commits: false
