name: Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: flcdrg/rss-to-readme@v1.2.7
        with:
          feed-url: https://david.gardiner.net.au/feed.xml
          readme-section: posts
          empty-commits: false
